# frozen_string_literal: true

source 'https://rubygems.org'

group :console do
  gem 'awesome_print', '~> 1.7'
end

group :development do
  gem 'rubocop',             '~> 1.6'
  gem 'rubocop-performance', '~> 1.9'
  gem 'rubocop-rspec',       '~> 2.1'
end

# Specify your gem's dependencies in fuubar.gemspec
gemspec
